# Имя подгружаемого модуля
KMOD    =  ng_hash

# Исходные и заголовочные файлы модуля
SRCS    =  ng_hash.h ng_hash.c hash.c hash.h hash_tcp.h hash_tcp.c

# Добавление сборочного файла модуля ядра
.include <bsd.kmod.mk>
